name: Docker CI

# 언제 실행할지 정의 (main 브랜치에 푸시할 때)
on:
  push:
    branches:
      - main

# 실행할 작업 정의
jobs:
  build:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행
    steps:
      # 1. 리포지토리 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Docker Buildx 설정 (고급 빌드 기능 사용)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 3. Docker 이미지 빌드
      - name: Build Docker image
        run: docker build -t coffebin/docker-react-app -f Dockerfile.dev .

      # 4. 테스트 실행 (프로젝트에 맞게 수정 필요)
      - name: Run tests
        run: docker run -e CI=true coffebin/docker-react-app npm test
        
      # 5. 배포 파일 압축 (deploy.zip 생성)
      - name: Create deployment package
        run: zip -r deploy.zip .

      # 6. Elastic Beanstalk에 배포
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: docker-react-app
          environment_name: Docker-react-app-env
          version_label: 12345
          region: ap-northeast-2
          deployment_package: deploy.zip